// <auto-generated />
namespace KbAbp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 去除重复的名称 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(去除重复的名称));
        
        string IMigrationMetadata.Id
        {
            get { return "201606070945350_去除重复的名称"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
